# Generated by Django 5.0.2 on 2024-02-29 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='product_variant_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product_variant'),
        ),
    ]
