# Generated by Django 5.0.2 on 2024-02-29 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_variant_product_variant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='product_variant',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
